/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akimovcg (https://sketchfab.com/akimovcg)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereum-3d-logo-de0c154b6f1c46639864a01360dd6aa0
title: Ethereum 3D logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/eth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={1}>
          <mesh geometry={nodes.Object_2.geometry} material={materials['default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eth.gltf')
